### ISSUE TITLE
Bad Request: message text is empty if no intent found

### ISSUE THREAD

**Issue by luizcarvalho** [manicholls/lita-api-ai#1]
When none intent is found, this error is generated.

```
Telegram API has returned the error. (ok: "false", error_code: "400", description: "Bad Request: message text is empty")
Full backtrace:
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/api.rb:69:in `call'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/api.rb:53:in `method_missing'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-telegram-0.1.0/lib/lita/adapters/telegram.rb:31:in `block in send_messages'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-telegram-0.1.0/lib/lita/adapters/telegram.rb:29:in `each'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-telegram-0.1.0/lib/lita/adapters/telegram.rb:29:in `send_messages'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:129:in `send_messages'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-api-ai-0.1.1/lib/lita/handlers/api_ai.rb:20:in `chat'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/callback.rb:31:in `public_send'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/callback.rb:31:in `call'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/event_router.rb:61:in `block in trigger'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/event_router.rb:59:in `map'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/event_router.rb:59:in `trigger'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:183:in `block in trigger'
/home/desenvolvimento/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/set.rb:324:in `each_key'
/home/desenvolvimento/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/set.rb:324:in `each'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:180:in `trigger'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:72:in `receive'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-telegram-0.1.0/lib/lita/adapters/telegram.rb:25:in `block in run'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:38:in `block in fetch_updates'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:33:in `each'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:33:in `fetch_updates'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:25:in `listen'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-telegram-0.1.0/lib/lita/adapters/telegram.rb:14:in `run'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:80:in `run'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita.rb:80:in `run'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/cli.rb:77:in `start'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/bin/lita:6:in `<top (required)>'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/bin/lita:22:in `load'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/bin/lita:22:in `<main>'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/desenvolvimento/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>
```

**Comment by manicholls** [comment]
Could you provide more context around what is happening and what you would expect to be different?

**Comment by luizcarvalho** [comment]
Ok, 

When I send, for instance, `Susie how are you?` my api.ai haven't any intent to match with this, not even `Default Fallback Intent`. So, I expect nothing is returned (this happen), but this error is generated and I think this should not happen. If nothing is returned, nothing should be sent... or not?

**Comment by manicholls** [comment]
I think this is expected in this case.  Keep in mind this project is simply a wrapper around the api.ai APIs.  It only sends off responses that don't match other Lita routes to API.ai in order to get a response.  If you don't have any fallback intent, then I'm not sure offhand how api.ai's API's are expected to behave.

**Comment by luizcarvalho** [comment]
Humm I understand. This only a incompatibility with Telegram API, it don't generate this error if nothing is sent. But, understand you.

Thank you anyway.

**Comment by manicholls** [comment]
Ok, I'll close off the issue.  If there is anything else I can help with let me know
